[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "spark"
version = "0.0.1"

dependencies = []

[project.optional-dependencies]
tests = [
  'pytest==7.3.1',
]

[tool.setuptools.packages]
find = {namespaces = false, exclude=['test']}